coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
    patch:
      default:
        target: 75%

comment:
  layout: "reach, diff, flags, files"

fixes:
  - "/home/runner/work/DesperateDevs.HelloWorld/DesperateDevs.HelloWorld/::"

flag_management:
  default_rules:
    carryforward: false
    statuses:
      - type: project
        target: auto
        threshold: 1%
      - type: patch
        target: 75%
  individual_flags:
    - name: HelloWorld
      paths:
        - src/HelloWorld
    - name: DesperateDevs.HelloOtherWorld
      paths:
        - src/DesperateDevs.HelloOtherWorld
