coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%

comment:
  layout: "reach, diff, flags, files"

codecov:
  disable_default_path_fixes: true

fixes:
  - "/home/runner/work/DesperateDevs.HelloWorld/DesperateDevs.HelloWorld/::"
