comment:
  layout: "reach, diff, flags, files"

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
    patch:
      default:
        target: 75%

fixes:
  - "/home/runner/work/DesperateDevs.HelloWorld/DesperateDevs.HelloWorld/::"

flag_management:
  default_rules:
    carryforward: true
    statuses:
      - type: project
        target: auto
        threshold: 1%
      - type: patch
        target: 75%
