name: Publish NuGet Packages

on:
  workflow_call:

jobs:
  pack:
    uses: sschmid/DotnetGitHubActions/.github/workflows/nuget_pack.yml@main
  publish:
    needs: pack
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: NuGet Packages
      - run: dotnet nuget push "*.nupkg" --api-key "${NUGET_API_KEY}" --skip-duplicate --source https://api.nuget.org/v3/index.json
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
